SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS user_courses;
DROP TABLE IF EXISTS lessons;
DROP TABLE IF EXISTS lesson_data;
DROP TABLE IF EXISTS courses;
DROP TABLE IF EXISTS resets;
DROP TABLE IF EXISTS sessions;
SET FOREIGN_KEY_CHECKS=1;
