SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS user_courses;
DROP TABLE IF EXISTS lessons;
DROP TABLE IF EXISTS courses;
DROP TABLE IF EXISTS resets;
DROP TABLE IF EXISTS sessions;
DROP TABLE IF EXISTS email_list;
SET FOREIGN_KEY_CHECKS=1;
